// <auto-generated />
using System;
using Margorak.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Margorak.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720125736_MoveEquipSlotToItemCategory")]
    partial class MoveEquipSlotToItemCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Margorak.Api.Models.ArmorStat", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmorValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EvasionValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("ArmorStats");
                });

            modelBuilder.Entity("Margorak.Api.Models.Attack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackRange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Attacks");
                });

            modelBuilder.Entity("Margorak.Api.Models.AttackDamage", b =>
                {
                    b.Property<int>("AttackId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DamageTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinDamage")
                        .HasColumnType("INTEGER");

                    b.HasKey("AttackId", "DamageTypeId");

                    b.HasIndex("DamageTypeId");

                    b.ToTable("AttackDamages");
                });

            modelBuilder.Entity("Margorak.Api.Models.BonusType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BonusTypes");
                });

            modelBuilder.Entity("Margorak.Api.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterRaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentMapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentMp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dexterity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Gold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxMp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vitality")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterClassId");

                    b.HasIndex("CharacterRaceId");

                    b.HasIndex("CurrentMapId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Margorak.Api.Models.CharacterClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CharacterClasses");
                });

            modelBuilder.Entity("Margorak.Api.Models.CharacterEquipment", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipSlotId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnedItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId", "EquipSlotId");

                    b.HasIndex("EquipSlotId");

                    b.HasIndex("OwnedItemId");

                    b.ToTable("CharacterEquipment");
                });

            modelBuilder.Entity("Margorak.Api.Models.CharacterRace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DexterityMod")
                        .HasColumnType("REAL");

                    b.Property<double>("IntelligenceMod")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("StrengthMod")
                        .HasColumnType("REAL");

                    b.Property<double>("VitalityMod")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("CharacterRaces");
                });

            modelBuilder.Entity("Margorak.Api.Models.Combatant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CombatantRaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoldLootMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoldLootMin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CombatantRaceId");

                    b.ToTable("Combatants");
                });

            modelBuilder.Entity("Margorak.Api.Models.CombatantAttack", b =>
                {
                    b.Property<int>("CombatantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AttackCount")
                        .HasColumnType("REAL");

                    b.HasKey("CombatantId", "AttackId");

                    b.HasIndex("AttackId");

                    b.ToTable("CombatantAttacks");
                });

            modelBuilder.Entity("Margorak.Api.Models.CombatantHabitat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmbushProbability")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CombatantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocX1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocX2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocY1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocY2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Probability")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TerrainTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CombatantId");

                    b.HasIndex("MapId");

                    b.HasIndex("TerrainTypeId");

                    b.ToTable("CombatantHabitats");
                });

            modelBuilder.Entity("Margorak.Api.Models.CombatantLoot", b =>
                {
                    b.Property<int>("CombatantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Probability")
                        .HasColumnType("INTEGER");

                    b.HasKey("CombatantId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("CombatantLoots");
                });

            modelBuilder.Entity("Margorak.Api.Models.CombatantRace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CombatantRaces");
                });

            modelBuilder.Entity("Margorak.Api.Models.CombatantResistance", b =>
                {
                    b.Property<int>("CombatantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResistanceTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("CombatantId", "ResistanceTypeId");

                    b.HasIndex("ResistanceTypeId");

                    b.ToTable("CombatantResistances");
                });

            modelBuilder.Entity("Margorak.Api.Models.ConsumableEffect", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EffectTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId", "EffectTypeId");

                    b.HasIndex("EffectTypeId");

                    b.ToTable("ConsumableEffects");
                });

            modelBuilder.Entity("Margorak.Api.Models.DamageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DamageTypes");
                });

            modelBuilder.Entity("Margorak.Api.Models.EffectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EffectTypes");
                });

            modelBuilder.Entity("Margorak.Api.Models.EquipSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EquipSlots");
                });

            modelBuilder.Entity("Margorak.Api.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemCategoryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Margorak.Api.Models.ItemBonus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonusTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BonusTypeId");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemBonuses");
                });

            modelBuilder.Entity("Margorak.Api.Models.ItemCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EquipSlotId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EquipSlotId");

                    b.ToTable("ItemCategories");
                });

            modelBuilder.Entity("Margorak.Api.Models.ItemDamage", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DamageTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinDamage")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId", "DamageTypeId");

                    b.HasIndex("DamageTypeId");

                    b.ToTable("ItemDamages");
                });

            modelBuilder.Entity("Margorak.Api.Models.ItemRequirement", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequirementTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId", "RequirementTypeId");

                    b.HasIndex("RequirementTypeId");

                    b.ToTable("ItemRequirements");
                });

            modelBuilder.Entity("Margorak.Api.Models.ItemResistance", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResistanceTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId", "ResistanceTypeId");

                    b.HasIndex("ResistanceTypeId");

                    b.ToTable("ItemResistances");
                });

            modelBuilder.Entity("Margorak.Api.Models.Level", b =>
                {
                    b.Property<int>("Value")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpRequiered")
                        .HasColumnType("INTEGER");

                    b.HasKey("Value");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("Margorak.Api.Models.Map", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClickRange")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SightRange")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("Margorak.Api.Models.MapInteraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MapInteractionCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.HasIndex("MapInteractionCategoryId");

                    b.ToTable("MapInteractions");
                });

            modelBuilder.Entity("Margorak.Api.Models.MapInteractionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MapInteractionCategories");
                });

            modelBuilder.Entity("Margorak.Api.Models.MapTile", b =>
                {
                    b.Property<int>("MapTileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TerrainId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XCoord")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YCoord")
                        .HasColumnType("INTEGER");

                    b.HasKey("MapTileId");

                    b.HasIndex("MapId");

                    b.HasIndex("TerrainId");

                    b.ToTable("MapTiles");
                });

            modelBuilder.Entity("Margorak.Api.Models.OwnedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ItemId");

                    b.ToTable("OwnedItems");
                });

            modelBuilder.Entity("Margorak.Api.Models.RequirementType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RequirementTypes");
                });

            modelBuilder.Entity("Margorak.Api.Models.ResistanceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ResistanceTypes");
                });

            modelBuilder.Entity("Margorak.Api.Models.ShopInteraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("MapInteractionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MapInteractionId")
                        .IsUnique();

                    b.ToTable("ShopInteractions");
                });

            modelBuilder.Entity("Margorak.Api.Models.TeleporterInteraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DestinationLocX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DestinationLocY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DestinationMapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MapInteractionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DestinationMapId");

                    b.HasIndex("MapInteractionId")
                        .IsUnique();

                    b.ToTable("TeleporterInteractions");
                });

            modelBuilder.Entity("Margorak.Api.Models.Terrain", b =>
                {
                    b.Property<int>("TerrainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Accessible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TerrainTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TerrainId");

                    b.HasIndex("TerrainTypeId");

                    b.ToTable("Terrains");
                });

            modelBuilder.Entity("Margorak.Api.Models.TerrainType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TerrainTypes");
                });

            modelBuilder.Entity("Margorak.Api.Models.WeaponStat", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackRange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackSpeed")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("WeaponStats");
                });

            modelBuilder.Entity("Margorak.Api.Models.ArmorStat", b =>
                {
                    b.HasOne("Margorak.Api.Models.Item", "Item")
                        .WithMany("ArmorStat")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Margorak.Api.Models.AttackDamage", b =>
                {
                    b.HasOne("Margorak.Api.Models.Attack", "Attack")
                        .WithMany("AttackDamages")
                        .HasForeignKey("AttackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Margorak.Api.Models.DamageType", "DamageType")
                        .WithMany("AttackDamages")
                        .HasForeignKey("DamageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attack");

                    b.Navigation("DamageType");
                });

            modelBuilder.Entity("Margorak.Api.Models.Character", b =>
                {
                    b.HasOne("Margorak.Api.Models.CharacterClass", "CharacterClass")
                        .WithMany("Characters")
                        .HasForeignKey("CharacterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Margorak.Api.Models.CharacterRace", "CharacterRace")
                        .WithMany("Characters")
                        .HasForeignKey("CharacterRaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Margorak.Api.Models.Map", "CurrentMap")
                        .WithMany("CurrentCharacters")
                        .HasForeignKey("CurrentMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterClass");

                    b.Navigation("CharacterRace");

                    b.Navigation("CurrentMap");
                });

            modelBuilder.Entity("Margorak.Api.Models.CharacterEquipment", b =>
                {
                    b.HasOne("Margorak.Api.Models.Character", "Character")
                        .WithMany("CharacterEquipment")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Margorak.Api.Models.EquipSlot", "EquipSlot")
                        .WithMany("CharacterEquipment")
                        .HasForeignKey("EquipSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Margorak.Api.Models.OwnedItem", "OwnedItem")
                        .WithMany("CharacterEquipment")
                        .HasForeignKey("OwnedItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("EquipSlot");

                    b.Navigation("OwnedItem");
                });

            modelBuilder.Entity("Margorak.Api.Models.Combatant", b =>
                {
                    b.HasOne("Margorak.Api.Models.CombatantRace", "CombatantRace")
                        .WithMany("Combatants")
                        .HasForeignKey("CombatantRaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CombatantRace");
                });

            modelBuilder.Entity("Margorak.Api.Models.CombatantAttack", b =>
                {
                    b.HasOne("Margorak.Api.Models.Attack", "Attack")
                        .WithMany("CombatantAttacks")
                        .HasForeignKey("AttackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Margorak.Api.Models.Combatant", "Combatant")
                        .WithMany("CombatantAttacks")
                        .HasForeignKey("CombatantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attack");

                    b.Navigation("Combatant");
                });

            modelBuilder.Entity("Margorak.Api.Models.CombatantHabitat", b =>
                {
                    b.HasOne("Margorak.Api.Models.Combatant", "Combatant")
                        .WithMany("CombatantHabitats")
                        .HasForeignKey("CombatantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Margorak.Api.Models.Map", "Map")
                        .WithMany("CombatantHabitats")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Margorak.Api.Models.TerrainType", "TerrainType")
                        .WithMany("CombatantHabitats")
                        .HasForeignKey("TerrainTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combatant");

                    b.Navigation("Map");

                    b.Navigation("TerrainType");
                });

            modelBuilder.Entity("Margorak.Api.Models.CombatantLoot", b =>
                {
                    b.HasOne("Margorak.Api.Models.Combatant", "Combatant")
                        .WithMany("CombatantLoots")
                        .HasForeignKey("CombatantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Margorak.Api.Models.Item", "Item")
                        .WithMany("CombatantLoots")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combatant");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Margorak.Api.Models.CombatantResistance", b =>
                {
                    b.HasOne("Margorak.Api.Models.Combatant", "Combatant")
                        .WithMany("CombatantResistances")
                        .HasForeignKey("CombatantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Margorak.Api.Models.ResistanceType", "ResistanceType")
                        .WithMany("CombatantResistances")
                        .HasForeignKey("ResistanceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combatant");

                    b.Navigation("ResistanceType");
                });

            modelBuilder.Entity("Margorak.Api.Models.ConsumableEffect", b =>
                {
                    b.HasOne("Margorak.Api.Models.EffectType", "EffectType")
                        .WithMany("ConsumableEffect")
                        .HasForeignKey("EffectTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Margorak.Api.Models.Item", "Item")
                        .WithMany("ConsumableEffect")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EffectType");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Margorak.Api.Models.Item", b =>
                {
                    b.HasOne("Margorak.Api.Models.ItemCategory", "ItemCategory")
                        .WithMany("Items")
                        .HasForeignKey("ItemCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemCategory");
                });

            modelBuilder.Entity("Margorak.Api.Models.ItemBonus", b =>
                {
                    b.HasOne("Margorak.Api.Models.BonusType", "BonusType")
                        .WithMany("ItemBonuses")
                        .HasForeignKey("BonusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Margorak.Api.Models.Item", "Item")
                        .WithMany("ItemBonuses")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonusType");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Margorak.Api.Models.ItemCategory", b =>
                {
                    b.HasOne("Margorak.Api.Models.EquipSlot", "EquipSlot")
                        .WithMany("ItemCategories")
                        .HasForeignKey("EquipSlotId");

                    b.Navigation("EquipSlot");
                });

            modelBuilder.Entity("Margorak.Api.Models.ItemDamage", b =>
                {
                    b.HasOne("Margorak.Api.Models.DamageType", "DamageType")
                        .WithMany("ItemDamages")
                        .HasForeignKey("DamageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Margorak.Api.Models.Item", "Item")
                        .WithMany("ItemDamages")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DamageType");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Margorak.Api.Models.ItemRequirement", b =>
                {
                    b.HasOne("Margorak.Api.Models.Item", "Item")
                        .WithMany("ItemRequirements")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Margorak.Api.Models.RequirementType", "RequirementType")
                        .WithMany("ItemRequirements")
                        .HasForeignKey("RequirementTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("RequirementType");
                });

            modelBuilder.Entity("Margorak.Api.Models.ItemResistance", b =>
                {
                    b.HasOne("Margorak.Api.Models.Item", "Item")
                        .WithMany("ItemResistances")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Margorak.Api.Models.ResistanceType", "ResistanceType")
                        .WithMany("ItemResistances")
                        .HasForeignKey("ResistanceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("ResistanceType");
                });

            modelBuilder.Entity("Margorak.Api.Models.MapInteraction", b =>
                {
                    b.HasOne("Margorak.Api.Models.Map", "Map")
                        .WithMany("Interactions")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Margorak.Api.Models.MapInteractionCategory", "Category")
                        .WithMany("Interactions")
                        .HasForeignKey("MapInteractionCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("Margorak.Api.Models.MapTile", b =>
                {
                    b.HasOne("Margorak.Api.Models.Map", "Map")
                        .WithMany("Tiles")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Margorak.Api.Models.Terrain", "Terrain")
                        .WithMany("MapTiles")
                        .HasForeignKey("TerrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");

                    b.Navigation("Terrain");
                });

            modelBuilder.Entity("Margorak.Api.Models.OwnedItem", b =>
                {
                    b.HasOne("Margorak.Api.Models.Character", "Character")
                        .WithMany("OwnedItems")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Margorak.Api.Models.Item", "Item")
                        .WithMany("OwnedItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Margorak.Api.Models.ShopInteraction", b =>
                {
                    b.HasOne("Margorak.Api.Models.MapInteraction", "MapInteraction")
                        .WithOne("ShopInteraction")
                        .HasForeignKey("Margorak.Api.Models.ShopInteraction", "MapInteractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MapInteraction");
                });

            modelBuilder.Entity("Margorak.Api.Models.TeleporterInteraction", b =>
                {
                    b.HasOne("Margorak.Api.Models.Map", "DestinationMap")
                        .WithMany("IncomingTeleporters")
                        .HasForeignKey("DestinationMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Margorak.Api.Models.MapInteraction", "MapInteraction")
                        .WithOne("TeleporterInteraction")
                        .HasForeignKey("Margorak.Api.Models.TeleporterInteraction", "MapInteractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DestinationMap");

                    b.Navigation("MapInteraction");
                });

            modelBuilder.Entity("Margorak.Api.Models.Terrain", b =>
                {
                    b.HasOne("Margorak.Api.Models.TerrainType", "TerrainType")
                        .WithMany("Terrains")
                        .HasForeignKey("TerrainTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TerrainType");
                });

            modelBuilder.Entity("Margorak.Api.Models.WeaponStat", b =>
                {
                    b.HasOne("Margorak.Api.Models.Item", "Item")
                        .WithMany("WeaponStat")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Margorak.Api.Models.Attack", b =>
                {
                    b.Navigation("AttackDamages");

                    b.Navigation("CombatantAttacks");
                });

            modelBuilder.Entity("Margorak.Api.Models.BonusType", b =>
                {
                    b.Navigation("ItemBonuses");
                });

            modelBuilder.Entity("Margorak.Api.Models.Character", b =>
                {
                    b.Navigation("CharacterEquipment");

                    b.Navigation("OwnedItems");
                });

            modelBuilder.Entity("Margorak.Api.Models.CharacterClass", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Margorak.Api.Models.CharacterRace", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Margorak.Api.Models.Combatant", b =>
                {
                    b.Navigation("CombatantAttacks");

                    b.Navigation("CombatantHabitats");

                    b.Navigation("CombatantLoots");

                    b.Navigation("CombatantResistances");
                });

            modelBuilder.Entity("Margorak.Api.Models.CombatantRace", b =>
                {
                    b.Navigation("Combatants");
                });

            modelBuilder.Entity("Margorak.Api.Models.DamageType", b =>
                {
                    b.Navigation("AttackDamages");

                    b.Navigation("ItemDamages");
                });

            modelBuilder.Entity("Margorak.Api.Models.EffectType", b =>
                {
                    b.Navigation("ConsumableEffect");
                });

            modelBuilder.Entity("Margorak.Api.Models.EquipSlot", b =>
                {
                    b.Navigation("CharacterEquipment");

                    b.Navigation("ItemCategories");
                });

            modelBuilder.Entity("Margorak.Api.Models.Item", b =>
                {
                    b.Navigation("ArmorStat");

                    b.Navigation("CombatantLoots");

                    b.Navigation("ConsumableEffect");

                    b.Navigation("ItemBonuses");

                    b.Navigation("ItemDamages");

                    b.Navigation("ItemRequirements");

                    b.Navigation("ItemResistances");

                    b.Navigation("OwnedItems");

                    b.Navigation("WeaponStat");
                });

            modelBuilder.Entity("Margorak.Api.Models.ItemCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Margorak.Api.Models.Map", b =>
                {
                    b.Navigation("CombatantHabitats");

                    b.Navigation("CurrentCharacters");

                    b.Navigation("IncomingTeleporters");

                    b.Navigation("Interactions");

                    b.Navigation("Tiles");
                });

            modelBuilder.Entity("Margorak.Api.Models.MapInteraction", b =>
                {
                    b.Navigation("ShopInteraction");

                    b.Navigation("TeleporterInteraction");
                });

            modelBuilder.Entity("Margorak.Api.Models.MapInteractionCategory", b =>
                {
                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("Margorak.Api.Models.OwnedItem", b =>
                {
                    b.Navigation("CharacterEquipment");
                });

            modelBuilder.Entity("Margorak.Api.Models.RequirementType", b =>
                {
                    b.Navigation("ItemRequirements");
                });

            modelBuilder.Entity("Margorak.Api.Models.ResistanceType", b =>
                {
                    b.Navigation("CombatantResistances");

                    b.Navigation("ItemResistances");
                });

            modelBuilder.Entity("Margorak.Api.Models.Terrain", b =>
                {
                    b.Navigation("MapTiles");
                });

            modelBuilder.Entity("Margorak.Api.Models.TerrainType", b =>
                {
                    b.Navigation("CombatantHabitats");

                    b.Navigation("Terrains");
                });
#pragma warning restore 612, 618
        }
    }
}
