// <auto-generated />
using System;
using Margorak.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Margorak.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260606134110_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Margorak.Api.Models.Map", b =>
                {
                    b.Property<int>("MapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("MapId");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("Margorak.Api.Models.MapTile", b =>
                {
                    b.Property<int>("MapTileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MapNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TerrainId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XCoord")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YCoord")
                        .HasColumnType("INTEGER");

                    b.HasKey("MapTileId");

                    b.HasIndex("MapId");

                    b.HasIndex("TerrainId");

                    b.ToTable("MapTiles");
                });

            modelBuilder.Entity("Margorak.Api.Models.Terrain", b =>
                {
                    b.Property<int>("TerrainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Accessible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TerrainId");

                    b.ToTable("Terrains");
                });

            modelBuilder.Entity("Margorak.Api.Models.MapTile", b =>
                {
                    b.HasOne("Margorak.Api.Models.Map", null)
                        .WithMany("Tiles")
                        .HasForeignKey("MapId");

                    b.HasOne("Margorak.Api.Models.Terrain", "Terrain")
                        .WithMany()
                        .HasForeignKey("TerrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Terrain");
                });

            modelBuilder.Entity("Margorak.Api.Models.Map", b =>
                {
                    b.Navigation("Tiles");
                });
#pragma warning restore 612, 618
        }
    }
}
